export default Object.freeze({
    //GLOBAL TYPES
    SET_LOADING: 'SET_LOADING',
    //TODO TYPES
    MARKED_TASKS: 'MARKED_TASKS',
    MARK_ALL_TASKS: 'MARK_ALL_TASKS',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    TOGGLE_CONFIRM_MODAL: 'TOGGLE_CONFIRM_MODAL',
    OPEN_EDIT_TASK_MODAL: 'OPEN_EDIT_TASK_MODAL',
    REMOVE_MARKED_TASKS: 'REMOVE_MARKED_TASKS',
    ADD_TASK: 'ADD_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    GET_TASK: 'GET_TASK',
    EDIT_TASK: 'EDIT_TASK',
    //SINGLETASK TYPES
    TOGGLE_SET_LOADING: 'TOGGLE_SET_LOADING',
    EDIT_SINGLETASK: 'EDIT_SINGLETASK',
    CLOSE_SINGLETASK_MODAL: 'CLOSE_SINGLETASK_MODAL'
});